### ISSUE TITLE
Causes tsc to stall indefinitely

### ISSUE THREAD

**Issue by cjroebuck** [syntax-tree/unist-util-visit#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.1.0

### Steps to reproduce

clone https://github.com/cjroebuck/next-build-stalled

```
npm i
npx tsc
```

typescript version 4.5.2 

(typescript version 4.4.3 does build ok)

### Expected behavior

build shouldn't stall

### Actual behavior

build stalls indefinitely

In order to get the build to pass, comment out [this line](https://github.com/cjroebuck/next-build-stalled/blob/main/src/index.d.ts#L2)

I suspect it's an issue with the unist-util-visit types?

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Next.js

**Comment by cjroebuck** [comment]
Please see corresponding issue in next.js https://github.com/vercel/next.js/issues/32193

**Comment by cjroebuck** [comment]
Looks like it could be a bug in tsc: https://github.com/microsoft/TypeScript/issues/46900

**Comment by ChristianMurphy** [comment]
Thanks for reaching out @cjroebuck and @benatkin! Sorry you ran into a spot of trouble.
This is indeed an issue in TypeScript, @stefanprobst also caught it in https://github.com/unifiedjs/unified/discussions/175 and narrowed it down to being a bug which was reported in TypeScript microsoft/TypeScript#46900 (which you've noted as well).
We're all waiting for a fix in TypeScript.
Pinning the TypeScript version to 4.4.3 is the work around for now.

**Comment by SilvaQ** [comment]
Excuse me, what is the current solution? I've looked at everything and I still can't find a solution.

I don't have a typescript project right now.
Pure JS projects do ` import {visit} from "unist-util-visit"; ` the CPU immediately overloads and vscode doesn't work properly

![image](https://user-images.githubusercontent.com/46706370/146736025-750a622d-955b-46f0-a93e-b3b21e22c624.png)

**Comment by SilvaQ** [comment]
I think this could be a temporary solution。
The idea is to solve the problem by switching versions of typescript。
Modify the default typescript mode of vscode as shown in the documentation below：
[using-the-workspace-version-of-typescript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript)

steps:
1. open vscode settings.json
2.  add typescript.tsdk filed
3. specify the typescript path you want to use

I installed the specified version of the current project：
```bash
yarn add typescript@4.4.4
```

Modified the vscode configuration file:
```json
       ... other fields here ....
"typescript.tsdk": "./node_modules/typescript/lib"
```
problem off for me now.

**Comment by kylekampy** [comment]
Alternative to pinning typescript version - you can pin `unist-util-visit` to `4.0.0` and also avoid the tsc hang.

**Comment by Saul-Mirone** [comment]
For anyone using pnpm:

https://github.com/Saul-Mirone/milkdown/blob/main/.pnpmfile.cjs

**Comment by siefkenj** [comment]
On TS 4.5 this only happens to me if I use the full `(node, index, parent) => ...` in my visit callback. If I just use `(node) => ...`, my typescript will actually compile...

Since I am only visiting one type of document, I was able to work around this issue by casing `visit` to any and the making a wrapper function.

```typescript
import { Element as XMLElement, Root } from "xast";
import { visit as origVisit } from "unist-util-visit";

const castVisit = origVisit as any;

/**
 * A wrapper around `unist-util-visit` to work around a typescript bug.
 * 
 * See
 * https://github.com/microsoft/TypeScript/issues/46900
 * https://github.com/syntax-tree/unist-util-visit/issues/33
 *
 */
export const xmlVisit = (
    ast: XMLElement | Root,
    test: (...args: any[]) => boolean,
    callback: (
        node: XMLElement,
        index: number | null,
        parent: XMLElement | undefined | null
    ) => any
) => {
    return castVisit(ast, test, callback);
};
```

**Comment by ChristianMurphy** [comment]
This has been resolved in TypeScript 4.6 https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/#improved-recursion-depth-checks
The fix has also been backported to 4.5

> You may already have this change because it was cherry-picked into TypeScript 4.5.3

**Comment by ThomasFKJorna** [comment]
Maybe I'm doing something wrong, but this problem still persists for me on Typescript 4.6.3

**Comment by wooorm** [comment]
it should work. Latest TS + latest this package. We’re using it in many places.

**Comment by jemgold** [comment]
has anyone figured out a good solve for this problem? Still having the same issue in 4.9.4

```ts
import type { Root } from 'mdast'

export const autolinkContract: U.Plugin<[], Root> = () => {
  return tree => {
    // tree is correctly cast to mdast.Root
    visit(tree, 'text', (node, index, parent) => {
      // node, index & parent eventually get narrowed correctly
      // but it's suuuuuper slow in VSCode
    })
  }
}
```

**Comment by ChristianMurphy** [comment]
@jemgold yes, use typescript 4.9.3 or newer in VSCode as well.
You are likely still seeing the issue because VSCode by default ships its own version of TypeScript, which is likely not as up-to-date as the one configured in your package.json file.
You can find out more on how to configure the TypeScript version VSCode uses in their docs:
https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions

**Comment by ChristianMurphy** [comment]
Locking this issue as:
1. not an issue in `unist-util-visit`, it was an upstream issue in TypeScript itself
2. it was solved a year ago by TypeScript

Feel free to open a discussion for any questions.
Or open a new issue if you believe a new issue has happened, which does not originate in TypeScript itself.
